### ISSUE TITLE
Radio button behaviour

### ISSUE THREAD

**Issue by frankier** [django-functest/django-functest#1]
I think the radio behaviour is slightly suboptimal. I think they might need slightly special behaviour vs other types of inputs would be:

1. Multiple matches are allowed exactly when all matches have the same name attribute
1. There should be an additional assertion that the given value is the same as the value of either: one of the matches, or an element with the same name (not sure which is better).

What do you think?

**Comment by spookylukey** [comment]
I think I addressed the first part in https://github.com/django-functest/django-functest/commit/f0367c86aefae58ab0288bb6ba16ee0830aaf07b#diff-d0e8285690d5150f05484831fc7204d3L182 - or did I misunderstand you?

**Comment by frankier** [comment]
Indeed radio button support is as I expected - I think I just somehow botched upgrading and still had 0.10. Great!
