### ISSUE TITLE
Cannot install using poetry

### ISSUE THREAD

**Issue by jerivas** [django-functest/django-functest#17]
I'm using the [poetry](https://python-poetry.org/) package manager and was very disappointed when it couldn't install `django-functest` with the following error:

```
Command ['/usr/local/bin/python', '-m', 'pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/88/af/e0/a0545a0ed79bd9db7048211f38710a034476e537fa40fb9a13fd8f66aa/faulthandler-3.2.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/88/af/e0/a0545a0ed79bd9db7048211f38710a034476e537fa40fb9a13fd8f66aa/faulthandler-3.2.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vgh5kkn2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vgh5kkn2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ng2z6d_f
           cwd: /tmp/pip-req-build-vgh5kkn2/
      Complete output (1 lines):
      ERROR: faulthandler is a builtin module since Python 3.3
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Upon investigation I stumbled across [this issue](https://github.com/python-poetry/poetry/issues/758#issuecomment-453864964) that explains the problem is caused by `if` statements to specify requirements (specifically `faulthandler` in the case of `django-functest`). The proposed solutions is to use environment markers instead.

**Comment by jerivas** [comment]
Here's an example implementation https://github.com/ray-project/ray/pull/3764/files

**Comment by spookylukey** [comment]
Thanks for the report, I've fixed on `master` now, I'll do a new release soon

**Comment by spookylukey** [comment]
@jerivas Actually it looks there are a bunch of things I need to fix/update before I can really do a new release, so don't expect it just yet - you should be able to install from git

**Comment by spookylukey** [comment]
1.1 is released now, hopefully should install no problem.
